### ISSUE TITLE
Using the LDAP user manager breaks on Azkaban 3.2+

### ISSUE THREAD

**Issue by chirpychips** [researchgate/azkaban-ldap-usermanager#10]
https://github.com/azkaban/azkaban/issues/775

We get the same error.

**Comment by jwoschitz** [comment]
Thanks for bringing this issue to our attention.

This has been resolved in https://github.com/researchgate/azkaban-ldap-usermanager/commit/ce3201d017e2732c508f58b98e373d190e5a7763 by shadowing the dependencies from org.apache.mina

The changes should be compatible to any Azkaban version >= 2.5.0. We tested it with 3.0, 3.2 and 3.16 (latest) builds.

The fix is also part of the [1.1.0 release](https://github.com/researchgate/azkaban-ldap-usermanager/releases/tag/1.1.0)
