### ISSUE TITLE
Unable to authenticate users as members of allowed groups

### ISSUE THREAD

**Issue by devangorder** [researchgate/azkaban-ldap-usermanager#3]
When I try to log in with my LDAP credentials, I see the error message: "Incorrect Login. User is not member of allowed groups". However, my user is definitely within the groups I have defined in the LDAP. I believe it is connecting fine to the LDAP, but it doesn't know how to map the LDAP groups to the Azkaban roles. Do we need a separate config file for that? How do I map 'azkaban_admin' to grant users within it the 'ADMIN' permissions?

Here's what I have the properties set as (sensitive info scrubbed):
user.manager.class=net.researchgate.azkaban.LdapUserManager
user.manager.ldap.host=xx.xx.xx.xx
user.manager.ldap.port=xxxxx
user.manager.ldap.useSsl=false
user.manager.ldap.userBase=ou=Users,dc=zzzz,dc=com
user.manager.ldap.userIdProperty=cn
user.manager.ldap.emailProperty=mail
user.manager.ldap.bindAccount=cn=DirectoryManager,dc=zzzz,dc=com
user.manager.ldap.bindPassword=qqqq
user.manager.ldap.allowedGroups=azkaban_admin,azkaban_readonly
user.manager.ldap.groupSearchBase=ou=Azkaban_Groups,dc=zzzz,dc=com
user.manager.ldap.embeddedGroups=true

**Comment by bashofmann** [comment]
Unfortunately LDAP servers seem to behave sometimes a bit differently when it comes to groups (see also https://github.com/researchgate/azkaban-ldap-usermanager/pull/2).

Could you post an example for results from your ldap server doing manual user and group lookups?

**Comment by devangorder** [comment]
Here's the ldif dump containing my azkaban groups from running an ldap search from the cli. Let me know if this helps.

> \## COMMAND RUN: ldapsearch -x -h [HOST] -p [PORT] -b "dc=zzzz,dc=com" -v
> 
> \# extended LDIF
> \#
> \# LDAPv3
> \# base <dc=zzzz,dc=com> with scope subtree
> \# filter: (objectclass=*)
> \# requesting: ALL
> \#
> 
> \# zzzz.com
> dn: dc=zzzz,dc=com
> objectClass: organization
> objectClass: dcObject
> dc: zzzz
> o: org
> 
> \# Users, zzzz.com
> dn: ou=Users,dc=zzzz,dc=com
> ou: Users
> objectClass: organizationalUnit
> 
> \# Azkaban_Groups, zzzz.com
> dn: ou=Azkaban_Groups,dc=zzzz,dc=com
> ou: Azkaban
> ou: Azkaban_Groups
> objectClass: organizationalUnit
> 
> \# azkaban_admin, Azkaban_Groups, zzzz.com
> dn: cn=azkaban_admin,ou=Azkaban_Groups,dc=zzzz,dc=com
> uniqueMember: cn=[USER],ou=Users,dc=zzzz,dc=com
> uniqueMember: cn=[USER],ou=Users,dc=zzzz,dc=com
> uniqueMember: cn=[USER],ou=Users,dc=zzzz,dc=com
> cn: azkaban_admin
> objectClass: top
> objectClass: groupOfUniqueNames
> 
> \# azkaban_readonly, Azkaban_Groups, zzzz.com
> dn: cn=azkaban_readonly,ou=Azkaban_Groups,dc=zzzz,dc=com
> uniqueMember: cn=[USER],ou=Users,dc=zzzz,dc=com
> cn: azkaban_readonly
> objectClass: top
> objectClass: groupOfUniqueNames
> 
> \# [USER], Users, zzzz.com
> dn: cn=[USER],ou=Users,dc=zzzz,dc=com
> sn: [USER]
> cn: [USER]
> objectClass: top
> objectClass: person
> objectClass: organizationalPerson
> userPassword:: [PASSWORD_HASH]
>

**Comment by jurgenweber** [comment]
I have the same issue but 'user.manager.ldap.embeddedGroups=true' is not relevant to, I removed the value from user.manager.ldap.allowedGroups and just left behind 'user.manager.ldap.allowedGroups=' and I can now login.

**Comment by devangorder** [comment]
Removing the embeddedGroups value and setting allowedGroups to empty allowed me to successfully authenticate with my ldap credentials, but there is no role management with this approach. Every user that is within Azkaban_Groups can login and is granted ADMIN access, however I wish to have some with only read only access (sub group azkaban_readonly). Have you been able to map different ldap groups to different roles within Azkaban?

**Comment by jurgenweber** [comment]
yeah, I hear you. 

No on the mapping but I am not fussed as I only have admin users. What I did want to do was deny users from being able to login. Right now everyone in login.

**Comment by bashofmann** [comment]
If I see this correctly from the information you provided the differences are:

* The field where the members of a group are stored is uniqueMember instead of memberuid
* This fields contains the users DN instead of UID

@devangorder can you check if this branch: https://github.com/researchgate/azkaban-ldap-usermanager/tree/issue-3-use-dn-for-allowed-groups

works for you.

You will need to set:

user.manager.ldap.groupMemberField=uniqueMember
user.manager.ldap.useDnForGroupMembership=true

If it does not you could try editing LdapUserManagerTest with your information and trying to run it agains your LDAP server and have a look if the group check starting at LdapUserManager::138 works correctly for your LDAP server.

It is kind of hard to test for me, because the servers I have accessible behave differently.

**Comment by jurgenweber** [comment]
well it's the difference I suppose between 'groupofnames' and a 'posixgroup'. I believe groupofnames is more the 'active directory' way of doing things where posixgroup is the unix way.

so in 'groupofnames' members are denoted by the 'member' attribute which are full DN's to the user.
and in a 'posixgroup' members are denoted by the 'memberuid' attribute which are just the UID's of the users in the group.

**Comment by jwoschitz** [comment]
@jurgenweber @devangorder the issues around the allowedGroups have been addressed in [v1.2.0](https://github.com/researchgate/azkaban-ldap-usermanager/releases/tag/1.2.0)

At the moment the project supports the two following LDAP group constructs:
* posixGroup:
this is default construct which is used when you have "user.manager.ldap.allowedGroups" defined but are not using "user.manager.ldap.embeddedGroups"

* groupOfNames:
This is supported only with an active overlay which provides a memberOf attribute for each user (e.g. should be the default within ActiveDirectory). In order to use this feature you need have "user.manager.ldap.allowedGroups" defined and need to set "user.manager.ldap.embeddedGroups=true"

For further reference see also https://www.rainingpackets.com/ldap-posixgroup-groupofnames

The "groupOfUniqueNames" objectClass is not supported yet.

I will close this particular issue for now since the underlying issues with non-matching allowedGroups has been addressed. If you should not be able model your group setup with the mentioned supported constructs, please open an additional ticket for enhancement to support also the groupOfUniqueNames objectclass.
